PYS_Web/Areas/Aprobaciones/Controllers/AyudaBusquedaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PYS_SQL;

namespace PYS_Web.Areas.Aprobaciones.Controllers
{
    public class AyudaBusquedaController : Controller
    {
        private SQL_TA_PERF_USUA sql = new SQL_TA_PERF_USUA();
        private SQL_TA_TIPO_DOCU_SIST sql2 = new SQL_TA_TIPO_DOCU_SIST();
        private SQL_TA_TIPO_EVAL sql3 = new SQL_TA_TIPO_EVAL();
        private SQL_TA_CATE_CARG sql4 = new SQL_TA_CATE_CARG();
        private SQL_TA_TIPO_MEDI_COMU sql5 = new SQL_TA_TIPO_MEDI_COMU();

        // GET: AyudaTabla
        public ActionResult Ayuda_Perfil()
        {
            ViewBag.buscar_TA_PERF_USUA = true;
            ViewBag.V_VB_LIST_TA_PERF_USUA = sql.Listado();
            ViewBag.title = "Tabla Perfil";
            return View("Index");
        }
        public ActionResult Ayuda_Documento()
        {
            ViewBag.buscar_TA_TIPO_DOCU_SIST = true;
            ViewBag.V_VB_LIST_TA_TIPO_DOCU_SIST = sql2.Listado(1);
            ViewBag.title = "Tabla Documentos";
            return View("Index");
        }
        public ActionResult Ayuda_Evaluacion()
        {
            ViewBag.buscar_TA_TIPO_EVAL = true;
            ViewBag.V_VB_LIST_TA_TIPO_EVAL = sql3.Listado();
            ViewBag.title = "Tabla Tipo Evaluación";
            return View("Index");
        }
        public ActionResult Ayuda_Cargo()
        {
            ViewBag.buscar_TA_CATE_CARG = true;
            ViewBag.V_VB_LIST_TA_CATE_CARG = sql4.Listado(1);
            ViewBag.title = "Tabla Categoría Cargo";
            return View("Index");
        }
        public ActionResult Ayuda_Tipo_Medio()
        {
            ViewBag.buscar_TA_TIPO_MEDI_COMU = true;
            ViewBag.V_VB_LIST_TA_TIPO_MEDI_COMU = sql5.Listado();
            ViewBag.title = "Tabla Tipo Medio Comunicación";
            return View("Index");
        }
    }
}

PYS_Web/Areas/Aprobaciones/Controllers/DocumentoAprobacionController.cs
using System;
using PYS_Entidad;
using PYS_SQL;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace PYS_Web.Areas.Aprobaciones.Controllers
{
    public class DocumentoAprobacionController : Controller
    {
        private SQL_TA_TIDO_APRO sql = new SQL_TA_TIDO_APRO();
        private SQL_TA_TIPO_DOCU_SIST sqlApoyo = new SQL_TA_TIPO_DOCU_SIST();
        // GET: DocumentoAprobacion
        public ActionResult Index()
        {
            ViewBag.List_Documento = sql.Listado(1);
            return View();
        }

        public ActionResult NewDocumento()
        {
            return View();
        }

        public ActionResult EditDocumento(E_TA_TIDO_APRO obj)
        {
            obj.FI_COD_EMPR = 1;
            ViewBag.getDocumento = sql.Buscar_Por_Codigo(obj.FS_COD_TIDO_SIST, obj.FI_COD_EMPR);
            return View();
        }

        //public ActionResult ReportDocumento()
        //{
        //    List<E_TA_TIDO_APRO> list = new List<E_TA_TIDO_APRO>();
        //    list = sql.Reporte(1);

        //    string ruta_capa_rep = "\\PYP_Reportes";
        //    string rptRuta = Path.GetDirectoryName(Path.GetDirectoryName(Server.MapPath(""))) + ruta_capa_rep;
        //    ReportDocument rd = new ReportDocument();
        //    rd.Load(Path.Combine(rptRuta, "Rpt_DocumentoAprobacion.rpt"));

        //    rd.SetDataSource(list);
        //    Response.Buffer = false;
        //    Response.ClearContent();
        //    Response.ClearHeaders();
        //    Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
        //    stream.Seek(0, SeekOrigin.Begin);
        //    //Response.AddHeader("Content-Disposition", "inline; filename=Authorization.pdf");
        //    return File(stream, "application/pdf", "Reporte_Documento_Aprobación.pdf");
        //}



        //public JsonResult validaExistenciaCod(string FS_COD_TIDO_SIST)
        //{
        //    return Json(!String.Equals(FS_COD_TIDO_SIST, "ABL"));
        //}

        public void SaveDocumento(E_TA_TIDO_APRO obj)
        {
            obj.FS_COD_USCR = "SHINTA";
            obj.FI_COD_EMPR = 1;
            sql.Insertar(obj);
        }

        // Validación - Verifica si Campo ya existe en DB y si existe en tabla de Apoyo
        [HttpPost]
        public JsonResult validaExistenciaCod(E_TA_TIDO_APRO obj, E_TA_TIPO_DOCU_SIST obj2)

        {
            obj = sql.Buscar_Por_Codigo(obj.FS_COD_TIDO_SIST, 1);
            obj2 = sqlApoyo.Buscar_Por_Codigo(obj2.FS_COD_TIDO_SIST, 1);
            if (obj.FS_COD_TIDO_SIST != "")
            {          
                return Json("Código ya existe en tabla");            
            }
            else if(obj2.FS_COD_TIDO_SIST == "")
            {
                return Json("Código de Doc. no existe");
            }
            else
                return Json(true);
        }

        [HttpPost]
        public JsonResult Guardar(E_TA_TIDO_APRO model)
        {



            var resp = new ResponseModel
            {
                response = true,
                error = ""
            };
            if (ModelState.IsValid)
            {
                SaveDocumento(model);
            }
            else
            {
                resp.response = false;
            }
            return Json(resp);
        }
        [HttpPost]
        public JsonResult Actualizar(E_TA_TIDO_APRO model)
        {



            var resp = new ResponseModel
            {
                response = true,
                error = ""
            };
            if (ModelState.IsValid)
            {
                UpdateDocumento(model);
            }
            else
            {
                resp.response = false;
            }
            return Json(resp);
        }
        public void UpdateDocumento(E_TA_TIDO_APRO obj)
        {
            obj.FS_COD_USMO = "SHINTA";
            obj.FI_COD_EMPR = 1;
            sql.Actualizar(obj);
        }

        public void DeleteDocumento(E_TA_TIDO_APRO obj)
        {
            obj.FI_COD_EMPR = 1;
            sql.Eliminar(obj);
        }
    }
}

PYS_Web/Areas/Aprobaciones/Views/DocumentoAprobacion/EditDocumento.cshtml
@using PYS_Entidad;
@{
    E_TA_TIDO_APRO obj = (E_TA_TIDO_APRO)ViewBag.getDocumento;
    Layout = null;
}
<form id="Frm_Documento_Aprobacion">
    <div class="modal-dialog modal-editar">
        <div class="modal-content">
            <div class="modal-header text-center ">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" id="btnCerrarDocumentoEdit">&times;</button>
                <h2>Editar Documento</h2>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.Label("Código Documento", new { @class = "control-label" })
                            <div class="input-group">
                                @Html.TextBoxFor(x => @obj.FS_COD_TIDO_SIST,
                               new {
                                   @class = "form-control search-query busqCod validaCodigo_3",
                                   @id = "TXT_FS_COD_TIDO_SIST",
                                   @disabled = "disabled"
                               })
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label for="TXT_FS_DES_TIDO_SIST" class="control-label" style="visibility:hidden">space</label>
                            <input class="form-control" id="TXT_FS_DES_TIDO_SIST" readonly>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            @Html.Label("Cantidad de niveles", new { @class = "control-label" })
                            @Html.TextBoxFor(x => @obj.FI_CAN_NIVE, new { @class = "form-control validaNumeros_2", @id = "TXT_FI_CAN_NIVE" })
                            @Html.ValidationMessageFor(x => @obj.FI_CAN_NIVE, null, new { @class = "label label-alert help-block" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="btn-group" data-toggle="radio-buttons" id="rdobtnGroup1">
                                <label class="btn btn-default">
                                    @Html.RadioButtonFor(model => @obj.FS_IND_APRO_ENTI, "S", new { @class = "radioDocumento" }) Centro Costo
                                </label>

                                <label class="btn btn-default">
                                    @Html.RadioButtonFor(model => @obj.FS_IND_APRO_ANEX, "S", new { @class = "radioDocumento" }) Anexo

                                </label>
                                <label class="btn btn-default">
                                    @Html.RadioButtonFor(model => @obj, "", new { @class = "radioDocumento", @id = "btn3" }) Ninguno
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="modal-footer a-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default" id="btnGrabar" onclick="Actualizar('@obj.FS_COD_TIDO_SIST');">
                                    <span class="glyphicon glyphicon-pencil glyphicon-editar"></span>
                                </button>
                                <button type="button" class="btn btn-default" id="btnCancelar" data-dismiss="modal">
                                    <span class="glyphicon glyphicon-remove glyphicon-cancelar"></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@Scripts.Render("~/bundles/jsValidacion")

<script type="text/javascript">

    $(document).ready(function () {
        select_FS_COD_TIDO_SIST();
        $(".radioDocumento").each(function (index, item) {
            $(item).click(function () {
                //'uncheck other Radiobutton.
                $('.radioDocumento').not(this).prop('checked', false);
            });
        });
        if (!$("#obj_FS_IND_APRO_ENTI").is(":checked") && !$("#obj_FS_IND_APRO_ANEX").is(":checked")) {
            $('#btn3').attr("checked", "checked");
        }

    })

    function select_FS_COD_TIDO_SIST() {
        $.ajax({
            type: 'GET',
            url: "@Url.Action("Ayuda_Documento", "AyudaBusqueda", new { Area = "Aprobaciones" })",
            success: function (data) {
                var codCampo = "#TXT_FS_COD_TIDO_SIST";
                var desCampo = "#TXT_FS_DES_TIDO_SIST";
                var nomForm = "#Frm_Documento_Aprobacion";

                var valCampo = $(codCampo).val();
                var busFila = $(data).find('tbody>tr.row-docu-apro:contains("' + valCampo + '")');
                var colCero = $(busFila).children("td:eq(0)");
                var colUno = $(busFila).children("td:eq(1)");
                if ($.trim($(colUno).html()) == '' || ($.trim($(colCero).html()) != valCampo) ||  $.trim(valCampo) == '') {
                    $(nomForm).validate().element(codCampo);
                    $(desCampo).val("");
                }
                else {
                    $(desCampo).val(colUno.html());
                }
            },
        error: function (res) {
            alertify.error("<strong>Error de conexión.</strong>");
        }
    });
    return false;
    }    
    function Actualizar(varCodEsta) {
        var form = $("#Frm_Documento_Aprobacion");
        if (form.validate() && $(form).valid()) {
            var prm = {
                FS_COD_TIDO_SIST: varCodEsta,
                FI_CAN_NIVE: $('#TXT_FI_CAN_NIVE').val(),
                FS_IND_APRO_ENTI: $('[id=obj_FS_IND_APRO_ENTI]:checked').val(),
                FS_IND_APRO_ANEX: $('[id=obj_FS_IND_APRO_ANEX]:checked').val()
                //--------------------------------------'[name=SelectedOrderType]:checked'
            };
            $.ajax({
                type: "post", url: "@Url.Action("Actualizar", "DocumentoAprobacion")", data: prm,
                success: function (res) {
                    alertify.success("<strong>Actualizado correctamente.</strong>");
                    Cancelar();
                    $("#btnCerrarDocumentoEdit").click();
                    $(".modal-backdrop").removeClass();
                },
                error: function (res) {
                    alertify.error("<strong>No se puede actualizar .</strong>");
                }
            });
        };
    };
</script>


PYS_Web/Areas/Aprobaciones/Views/DocumentoAprobacion/NewDocumento.cshtml

@model PYS_Entidad.E_TA_TIDO_APRO
@{
    Layout = null;
}

<script>
    function frm_buscar_COD_TIDO_SIST() {
        $.ajax({
            type: "post", url: "@Url.Action("Ayuda_Documento", "AyudaBusqueda")",
            success: function (res) {
                $("#ViewModal2").html(res);
                $("#btnViewModal2").click();
            },
            error: function (res) {
                alertify.error("<strong>Error de conexión.</strong>");
            }
        });
    };
</script>

@using (Html.BeginForm("Guardar", "DocumentoAprobacion", FormMethod.Post, new { id = "Frm_Documento_Aprobacion" }))
{
    <div class="modal-dialog" style="border-radius:10px;">
        <div class="modal-content">
            <div class="modal-header text-center">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" id="btnCerrarDocumento">&times;</button>
                <h3>Nuevo Registro</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.Label("Código Documento", new { @class = "control-label" })
                            <div class="input-group">
                                @Html.TextBoxFor(x => x.FS_COD_TIDO_SIST, new { @class = "form-control search-query validaCodigo_3", @id = "TXT_FS_COD_TIDO_SIST" })
                                <span class="input-group-btn">
                                    <button id="btnBuscar" class="btn btn-default cancel btn-buscar" data-toggle="tooltip" title="Buscar" type="button" 
                                            onclick="frm_buscar_COD_TIDO_SIST();" disableValidation="true">
                                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                    </button>
                                </span>
                            </div>
                            @Html.ValidationMessageFor(x => x.FS_COD_TIDO_SIST, null, new { @class = "label label-alert help-block" })
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label for="TXT_FS_DES_TIDO_SIST" class = "control-label" style="visibility:hidden">space</label>
                            <input class="form-control" id="TXT_FS_DES_TIDO_SIST" readonly>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            @Html.Label("Cantidad de niveles", new { @class = "control-label" })
                            @Html.TextBoxFor(x => x.FI_CAN_NIVE, new { @class = "form-control txtCantidadNivel validaNumeros_2", @value = 0, @id = "TXT_FI_CAN_NIVE" })
                            @Html.ValidationMessageFor(x => x.FI_CAN_NIVE, null, new { @class = "label label-alert help-block" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="btn-group" data-toggle="radio-buttons" id="rdobtnGroup1">
                                <label class="btn btn-default">
                                    @Html.RadioButtonFor(model => model.FS_IND_APRO_ENTI, "S", new { @class = "radioDocumento" }) Centro Costo
                                </label>

                                <label class="btn btn-default">
                                    @Html.RadioButtonFor(model => model.FS_IND_APRO_ANEX, "S", new { @class = "radioDocumento" }) Anexo

                                </label>
                                <label class="btn btn-default">
                                    @Html.RadioButtonFor(model => model.FS_IND_APRO_ANEX, "N", new { @class = "radioDocumento", Checked = "checked" }) Ninguno
                                </label>
                            </div>
                        </div>
                    </div>
                        <div class="col-sm-12">
                            <div class="modal-footer a-center">
                                <div class="btn-group">
                                    <button id="btnGuardar" type="submit" class="btn btn-default">
                                    <span class="glyphicon glyphicon-floppy-disk glyphicon-guardar"></span></button>
                                    <button class="btn btn-default cancel"value="Cancel" id="btnCancelar" data-dismiss="modal">
                                    <span class="glyphicon glyphicon-remove glyphicon-cancelar"></span></button>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
        <div class="modal fade" id="ViewModal2" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
            <!--- Body del modal de tabla aquí-->
        </div>
        <div class="col-sm-2 a-left no-padd">
            <button data-toggle="modal" data-target="#ViewModal2" id="btnViewModal2" onclick="" hidden="hidden" type="button">Mostrar</button>
        </div>
@Scripts.Render("~/bundles/jsValidacion")

<script>
        // Función - Recibe aviso de existencia de Código en tabla
        function validar_existencia_FS_COD_TIDO_SIST() {
              $.ajax({
                 type: 'GET',
                 url: "@Url.Action("Index", "DocumentoAprobacion")",
                  success: function (data) {
                      var valCampo = $('#TXT_FS_COD_TIDO_SIST').val();

                      // Busca coincidencia
                      var busColumna = $(data).find('#tblDocumento td.col-cod-tido-sist:contains("' + valCampo + '")');
                     if (busColumna.html() == valCampo) {
                         alertify.confirm('Código ya existe en tabla, ¿desea actualizarlo?', function (e) {
                             if (e) {         
                                 $('#ViewModal').modal('toggle');
                                 $('#ViewModal').one('hidden.bs.modal', function (e) {
                                     EditarDocu(valCampo);
                                 })
                             }
                             else {
                                 return false;
                             }
                         });
                     }
                 },
                 error: function (res) {
                     alertify.error("<strong>Error de conexión.</strong>");
                 }
             });

        }

        // Manejo de RadioButtonFor
        $(".radioDocumento").each(function (index, item) {
            $(item).click(function () {
                $('.radioDocumento').not(this).prop('checked', false);
            });
        });
      
        function select_FS_COD_TIDO_SIST() {
            $.ajax({
                type: 'GET',
                url: "@Url.Action("Ayuda_Documento", "AyudaBusqueda", new { Area = "Aprobaciones" })",
                success: function (data) {
                    var codCampo = "#TXT_FS_COD_TIDO_SIST";
                    var desCampo = "#TXT_FS_DES_TIDO_SIST";
                    var nomForm = "#Frm_Documento_Aprobacion";

                    var valCampo = $(codCampo).val();
                    var busFila = $(data).find('tbody>tr.row-docu-apro:contains("' + valCampo + '")');
                    var colCero = $(busFila).children("td:eq(0)");
                    var colUno = $(busFila).children("td:eq(1)");
                    if ($.trim($(colUno).html()) == '' || ($.trim($(colCero).html()) != valCampo) ||  $.trim(valCampo) == '') {
                        $(nomForm).validate().element(codCampo);
                        $(desCampo).val("");
                    }
                    else {                       
                        $(desCampo).val(colUno.html());
                    }
                },
            error: function (res) {
                alertify.error("<strong>Error de conexión.</strong>");
            }
        });
        return false;
        }         

        // Obtener la desc. correspondiente al Código Documento al presionar Enter y verificar si ya existe en tabla
    $('#TXT_FS_COD_TIDO_SIST').keydown(function (e) {
            if (e.keyCode == 13) {
                validar_existencia_FS_COD_TIDO_SIST();
                select_FS_COD_TIDO_SIST();
            }
        });
    // Submit de formulario
        $('#Frm_Documento_Aprobacion').submit(function () {          
            var form = $(this);
            validar_existencia_FS_COD_TIDO_SIST();
            if (form.validate() && $(form).valid()) {
                form.ajaxSubmit({
                    dataType: 'JSON',
                    type: 'POST',
                    url: form.attr('action'),
                    success: function (res) {
                        if (res.response) {
                            alertify.success("<strong>Registrado correctamente.</strong>");
                            Cancelar();
                            $("#btnCerrarDocumento").click();
                            $(".modal-backdrop").removeClass();
                        }
                        else {
                            return false;
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        alertify.error("<strong>" + errorThrown + "</strong>");
                    }
                });
            }
            return false;
        });
                </script>
}