PYS_Web/Areas/Aprobaciones/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PYS_Web.Areas.Aprobaciones.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        // GET: Aprobaciones/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

PYS_Web/Areas/Finanzas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PYS_Web.Areas.Finanzas.Controllers
{
    public class HomeController : Controller
    {
        // GET: Finanzas/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

PYS_Web/Areas/Logistica/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PYS_Web.Areas.Logistica.Controllers
{
    public class HomeController : Controller
    {
        // GET: Logistica/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

PYS_Web/Areas/RR_HH/Controllers/CategoriaCargoController.cs
using PYS_Entidad;
using PYS_SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;


namespace PYS_Web.Areas.RR_HH.Controllers
{
    public class CategoriaCargoController : Controller
    {
        private SQL_TA_CATE_CARG sql = new SQL_TA_CATE_CARG();
        public ActionResult Index()
        {
            ViewBag.List_Categoria_Cargo = sql.Listado(1);
            return View();
        }

        public ActionResult NewCategoriaCargo()
        {
            return View();
        }

        public ActionResult EditCategoriaCargo(E_TA_CATE_CARG obj)
        {
            obj.FI_COD_EMPR = 1;
            ViewBag.getCategoriaCargo = sql.Buscar_Por_Codigo(obj.FS_COD_CCAR, obj.FI_COD_EMPR);
            return View();
        }


        //public ActionResult ReportCategoriaCargo()
        //{
        //    List<E_TA_CATE_CARG> list = new List<E_TA_CATE_CARG>();
        //    list = sql.Reporte(1);

        //    string ruta_capa_rep = "\\PYS_Reportes";
        //    string rptRuta = Path.GetDirectoryName(Path.GetDirectoryName(Server.MapPath(""))) + ruta_capa_rep;
        //    ReportDocument rd = new ReportDocument();
        //    rd.Load(Path.Combine(rptRuta, "Rpt_Categoria.rpt"));

        //    rd.SetDataSource(list);
        //    Response.Buffer = false;
        //    Response.ClearContent();
        //    Response.ClearHeaders();
        //    Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
        //    stream.Seek(0, SeekOrigin.Begin);
        //    //Response.AddHeader("Content-Disposition", "inline; filename=Authorization.pdf");
        //    return File(stream, "application/pdf", "Reporte_Categoria.pdf");
        //}
        public void SaveCategoriaCargo(E_TA_CATE_CARG obj)
        {
            obj.FS_COD_USCR = "shinta";
            obj.FI_COD_EMPR = 1;
            sql.Insertar(obj);
        }

        [HttpPost]
        public JsonResult Guardar(E_TA_CATE_CARG model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                SaveCategoriaCargo(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }
        public JsonResult Actualizar(E_TA_CATE_CARG model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                UpdateCategoriaCargo(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }




        public void UpdateCategoriaCargo(E_TA_CATE_CARG obj)
        {
            obj.FS_COD_USMO = "shinta";
            obj.FI_COD_EMPR = 1;
            sql.Actualizar(obj);
        }
        public void DeleteCategoriaCargo(E_TA_CATE_CARG obj)
        {
            obj.FI_COD_EMPR = 1;
            sql.Eliminar(obj);
        }

        // Validación - Verifica si Campo FS_COD_CCAR existe en DB 
        [HttpPost]
        public JsonResult validaExistenciaCOD_CCAR(E_TA_CATE_CARG obj)
        {
            obj = sql.Buscar_Por_Codigo(obj.FS_COD_CCAR, 1);
            if (obj.FS_COD_CCAR == "")
            {
                return Json(true);
            }
            else
                return Json("Código ya existe");
        }
    }
}

PYS_Web/Areas/RR_HH/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PYS_Web.Areas.RR_HH.Controllers
{
    public class HomeController : Controller
    {
        // GET: RR_HH/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

PYS_Web/Areas/RR_HH/Controllers/MedioCaptacionController.cs
using System;
using System.Collections.Generic;
using PYS_SQL;
using PYS_Entidad;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace PYS_Web.Areas.RR_HH.Controllers
{
    public class MedioCaptacionController : Controller
    { 
    private SQL_TA_MEDI_CAPT sql = new SQL_TA_MEDI_CAPT();
    public ActionResult Index()
    {
        ViewBag.List_Medio = sql.Listado();

        return View();
    }

    public ActionResult NewMedio()
    {
        return View();
    }

    public ActionResult EditMedio(E_TA_MEDI_CAPT obj)
    {
        ViewBag.getMedio = sql.Buscar_Por_Codigo(obj.FS_COD_MEDI_CAPT);
        return View();
    }


        //public ActionResult ReportMedio()
        //{
        //    List<E_TA_MEDI_CAPT> list = new List<E_TA_MEDI_CAPT>();
        //    list = sql.Reporte();

        //    string ruta_capa_rep = "\\PYP_Reportes";
        //    string rptRuta = Path.GetDirectoryName(Path.GetDirectoryName(Server.MapPath(""))) + ruta_capa_rep;
        //    ReportDocument rd = new ReportDocument();
        //    rd.Load(Path.Combine(rptRuta, "Rpt_Categoria.rpt"));

        //    rd.SetDataSource(list);
        //    Response.Buffer = false;
        //    Response.ClearContent();
        //    Response.ClearHeaders();
        //    Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
        //    stream.Seek(0, SeekOrigin.Begin);
        //    //Response.AddHeader("Content-Disposition", "inline; filename=Authorization.pdf");
        //    return File(stream, "application/pdf", "Reporte_Medio_Captacion.pdf");
        //}
        [HttpPost]
        public JsonResult Guardar(E_TA_MEDI_CAPT model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                SaveMedio(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }
        public void SaveMedio(E_TA_MEDI_CAPT obj)
    {
        obj.FS_COD_USCR = "shinta";
        sql.Insertar(obj);
    }

        [HttpPost]
        public JsonResult Actualizar(E_TA_MEDI_CAPT model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                UpdateMedio(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }
        public void UpdateMedio(E_TA_MEDI_CAPT obj)
        {
            obj.FS_COD_USMO = "shinta";
            sql.Actualizar(obj);

        }

        public void DeleteMedio(E_TA_MEDI_CAPT obj)
    {
        sql.Eliminar(obj);
    }
        // Validación - Verifica si Campo FS_COD_MEDI_CAPT existe en DB 
        [HttpPost]
        public JsonResult validaExistenciaMEDI_CAPT(E_TA_MEDI_CAPT obj)
        {
            obj = sql.Buscar_Por_Codigo(obj.FS_COD_MEDI_CAPT);
            if (obj.FS_COD_MEDI_CAPT == "")
            {
                return Json(true);
            }
            else
                return Json("Código ya existe");
        }
    }
}

PYS_Web/Areas/RR_HH/Controllers/MotivoEvaluacionController.cs
using PYS_Entidad;
using PYS_SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using CrystalDecisions.CrystalReports.Engine;


namespace PYS_Web.Areas.RR_HH.Controllers
{
    public class MotivoEvaluacionController : Controller
    {
        private SQL_TA_MOTI_EVAL sql = new SQL_TA_MOTI_EVAL();

        // GET: Categoria
        public ActionResult Index()
        {
            ViewBag.List_Motivo_Evaluacion = sql.Listado();

            return View();
        }

        public ActionResult NewMotivoEvaluacion()
        {
            return View();
        }

        public ActionResult EditMotivoEvaluacion(E_TA_MOTI_EVAL obj)
        {
            ViewBag.getMotivoEvaluacion = sql.Buscar_Por_Codigo(obj.FS_COD_MOTI_EVAL);
            return View();
        }


        //public ActionResult ReportPerfil()
        //{
        //    List<E_TA_MOTI_EVAL> list = new List<E_TA_MOTI_EVAL>();
        //    list = sql.Reporte();

        //    string ruta_capa_rep = "\\PYP_Reportes";
        //    string rptRuta = Path.GetDirectoryName(Path.GetDirectoryName(Server.MapPath(""))) + ruta_capa_rep;
        //    ReportDocument rd = new ReportDocument();
        //    rd.Load(Path.Combine(rptRuta, "Rpt_Categoria.rpt"));

        //    rd.SetDataSource(list);
        //    Response.Buffer = false;
        //    Response.ClearContent();
        //    Response.ClearHeaders();
        //    Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
        //    stream.Seek(0, SeekOrigin.Begin);
        //    //Response.AddHeader("Content-Disposition", "inline; filename=Authorization.pdf");
        //    return File(stream, "application/pdf", "Reporte_Categoria.pdf");
        //}
        public void SaveMotivoEvaluacion(E_TA_MOTI_EVAL obj)
        {
            obj.FS_COD_USCR = "shinta";
            sql.Insertar(obj);
        }

        [HttpPost]
        public JsonResult Guardar(E_TA_MOTI_EVAL model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                SaveMotivoEvaluacion(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }
        [HttpPost]
        public JsonResult Actualizar(E_TA_MOTI_EVAL model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                UpdateMotivoEvaluacion(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }
        public void UpdateMotivoEvaluacion(E_TA_MOTI_EVAL obj)
        {
            obj.FS_COD_USMO = "shinta";
            sql.Actualizar(obj);
        }
        public void DeleteMotivoEvaluacion(E_TA_MOTI_EVAL obj)
        {
            sql.Eliminar(obj);
        }
        // Validación - Verifica si Campo FS_COD_MOTI_EVAL existe en DB 
        [HttpPost]
        public JsonResult validaExistenciaCOD_MOTI_EVAL(E_TA_MOTI_EVAL obj)
        {
            obj = sql.Buscar_Por_Codigo(obj.FS_COD_MOTI_EVAL);
            if (obj.FS_COD_MOTI_EVAL == "" )
            {
                return Json(true);
            }
            else
                return Json("Código ya existe");
        }
    }
}

PYS_Web/Areas/RR_HH/Controllers/TipoEvaluacionController.cs
using PYS_Entidad;
using PYS_SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using CrystalDecisions.CrystalReports.Engine;

namespace PYS_Web.Areas.RR_HH.Controllers
{
    public class TipoEvaluacionController : Controller
    {
        private SQL_TA_TIPO_EVAL sql = new SQL_TA_TIPO_EVAL();

        // GET: Categoria
        public ActionResult Index()
        {
            ViewBag.List_Tipo_Evaluacion = sql.Listado();

            return View();
        }

        public ActionResult NewTipoEvaluacion()
        {
            return View();
        }

        public ActionResult EditTipoEvaluacion(E_TA_TIPO_EVAL obj)
        {
            ViewBag.getTipoEvaluacion = sql.Buscar_Por_Codigo(obj.FS_TIP_EVAL);
            return View();
        }


        //public ActionResult ReportPerfil()
        //{
        //    List<E_TA_TIPO_EVAL> list = new List<E_TA_TIPO_EVAL>();
        //    list = sql.Reporte();

        //    string ruta_capa_rep = "\\PYP_Reportes";
        //    string rptRuta = Path.GetDirectoryName(Path.GetDirectoryName(Server.MapPath(""))) + ruta_capa_rep;
        //    ReportDocument rd = new ReportDocument();
        //    rd.Load(Path.Combine(rptRuta, "Rpt_Categoria.rpt"));

        //    rd.SetDataSource(list);
        //    Response.Buffer = false;
        //    Response.ClearContent();
        //    Response.ClearHeaders();
        //    Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
        //    stream.Seek(0, SeekOrigin.Begin);
        //    //Response.AddHeader("Content-Disposition", "inline; filename=Authorization.pdf");
        //    return File(stream, "application/pdf", "Reporte_Categoria.pdf");
        //}
        public void SaveTipoEvaluacion(E_TA_TIPO_EVAL obj)
        {
            obj.FS_COD_USCR = "shinta";
            sql.Insertar(obj);
        }

        [HttpPost]
        public JsonResult Guardar(E_TA_TIPO_EVAL model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                SaveTipoEvaluacion(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }

        [HttpPost]
        public JsonResult Actualizar(E_TA_TIPO_EVAL model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                UpdateTipoEvaluacion(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }
        public void UpdateTipoEvaluacion(E_TA_TIPO_EVAL obj)
        {
            obj.FS_COD_USMO = "shinta";
            sql.Actualizar(obj);
        }
        public void DeleteTipoEvaluacion(E_TA_TIPO_EVAL obj)
        {
            sql.Eliminar(obj);
        }

        // Validación - Verifica si Campo FS_TIP_EVAL existe en DB 
        [HttpPost]
        public JsonResult validaExistenciaTIP_EVAL(E_TA_TIPO_EVAL obj)
        {
            obj = sql.Buscar_Por_Codigo(obj.FS_TIP_EVAL);
            if (obj.FS_TIP_EVAL == "")
            {
                return Json(true);
            }
            else
                return Json("Código ya existe");
        }
    }
}

PYS_Web/Areas/Tesoreria/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PYS_Web.Areas.Tesoreria.Controllers
{
    public class HomeController : Controller
    {
        // GET: Tesoreria/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

PYS_Web/Areas/Ventas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PYS_Web.Areas.Ventas.Controllers
{
    public class HomeController : Controller
    {
        // GET: Ventas/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

PYS_Web/Views/Home/SideMenu.cshtml
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar" id="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/Content/AdminLTE/img/LOGO_LILA SOLO.jpg" class="img-rounded" alt="User Image">
            </div>
         
            <div class="pull-left info user-panel">
                
                <p style="font-size:0.9em"> @ViewBag.User </p>
                <a href=""><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <br />
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu"><li class="header">Menú</li></ul>
        <!-------------------------- Menu 1 -------------------------->
        <ul class="sidebar-menu ocultar" data-widget="tree" id="menuAprobacion">


            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="active"><a href="index.html"><i class="fa fa-circle"></i> Dashboard v1</a></li>
                    <li><a href="index2.html"><i class="fa fa-circle"></i> Dashboard v2</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-files-o"></i>
                    <span>Configuraciones</span>     
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>          
                </a>
                <ul class="treeview-menu">
                    <li><a id="btnPerfilesApro" href="@Url.Action("Index", "PerfilAprobadores", new { Area = "Aprobaciones" },null)" data-navAjax="true"><i class="fa fa-circle"></i>Perfiles</a></li>
                    <li><a id="btnEstados" href="@Url.Action("Index","EstadoAprobacion", new { Area = "Aprobaciones" },null)" data-navAjax="true"><i class="fa fa-circle"></i>Estado aprobación</a></li>
                    <li><a id="btnDocumentos" href="@Url.Action("Index","DocumentoAprobacion", new { Area = "Aprobaciones" },null)" data-navAjax="true"><i class="fa fa-circle"></i>Documento aprobación</a></li>
                    
                </ul>
            </li>
            <li>
                <a href="pages/widgets.html">
                    <i class="fa fa-th"></i> <span>Widgets</span>               
                </a>
            </li>
            <li class="treeview">
                <a href="#" style="margin-bottom:0px">
                    <i class="fa fa-pie-chart"></i>
                    <span style="margin-left:-3px !important">Charts</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/charts/chartjs.html"><i class="fa fa-circle"></i> ChartJS</a></li>
                    <li><a href="pages/charts/morris.html"><i class="fa fa-circle"></i> Morris</a></li>
                    <li><a href="pages/charts/flot.html"><i class="fa fa-circle"></i> Flot</a></li>
                    <li><a href="pages/charts/inline.html"><i class="fa fa-circle"></i> Inline charts</a></li>
                </ul>
            </li>
        </ul>
        <!-------------------------- Menu 2 -------------------------->
        <ul class="sidebar-menu ocultar" data-widget="tree" id="menuRecursos">
            <li>
                <a href="pages/calendar.html">
                    <i class="fa fa-calendar"></i> <span>Planilla</span>
                    
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-share"></i> <span>Gestión Personal</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-circle"></i> Postulantes
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Index", "MedioCaptacion", new { Area = "RR_HH" },null)" data-navAjax="true"
                                   id="btnMedioCaptacion"><i class="fa fa-circle"></i>Medio captación</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "TipoMedioComunicacion", new { Area = "RR_HH" },null)" data-navAjax="true"
                                   id="btnTipoMedioComu"><i class="fa fa-circle"></i>Tipo medio comunicación</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "MedioComunicacion", new { Area = "RR_HH" },null)" data-navAjax="true"
                                   id="btnMedioComu"><i class="fa fa-circle"></i>Medio comunicación</a>
                            </li>
                            <li class="treeview">
                                <a href="#">
                                    <i class="fa fa-circle"></i> Level Two
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>
                                <ul class="treeview-menu">
                                    <li><a href="#"><i class="fa fa-circle"></i> Level Three</a></li>
                                    <li><a href="#"><i class="fa fa-circle"></i> Level Three</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-circle"></i> Evaluación
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                <a href="@Url.Action("Index", "CategoriaCargo", new { Area = "RR_HH" },null)" data-navAjax="true"
                                   id="btnCategoriaCargo"><i class="fa fa-circle"></i>Categoria Cargo Laboral</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "TipoEvaluacion", new { Area = "RR_HH" },null)" data-navAjax="true"
                                   id="btnTipoEvaluacion"><i class="fa fa-circle"></i>Tipo Evaluación</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "EvaluacionDesempeño", new { Area = "RR_HH" },null)" data-navAjax="true"
                                   id="btnEvaluacionDesempeño"><i class="fa fa-circle"></i>Evaluación Desempeño</a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "MotivoEvaluacion", new { Area = "RR_HH" },null)" data-navAjax="true"
                                   id="btnMotivoEvaluacion"><i class="fa fa-circle"></i>Motivo Evaluación</a>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#"><i class="fa fa-circle"></i> Desempeño</a></li>
                    <li><a href="#"><i class="fa fa-circle"></i> Competencia</a></li>
                    <li><a href="#"><i class="fa fa-circle"></i> Capacitación</a></li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Link</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/forms/general.html"><i class="fa fa-circle"></i> General Elements</a></li>
                    <li><a href="pages/forms/advanced.html"><i class="fa fa-circle"></i> Advanced Elements</a></li>
                    <li><a href="pages/forms/editors.html"><i class="fa fa-circle"></i> Editors</a></li>
                </ul>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-table"></i> <span>Link</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/tables/simple.html"><i class="fa fa-circle"></i> Simple tables</a></li>
                    <li><a href="pages/tables/data.html"><i class="fa fa-circle"></i> Data tables</a></li>
                </ul>
            </li>

            <li>
                <a href="pages/mailbox/mailbox.html">
                    <i class="fa fa-envelope"></i> <span>Link</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder"></i> <span>Link</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="pages/examples/invoice.html"><i class="fa fa-circle"></i> Invoice</a></li>
                    <li><a href="pages/examples/profile.html"><i class="fa fa-circle"></i> Profile</a></li>
                    <li><a href="pages/examples/login.html"><i class="fa fa-circle"></i> Login</a></li>
                    <li><a href="pages/examples/register.html"><i class="fa fa-circle"></i> Register</a></li>
                    <li><a href="pages/examples/lockscreen.html"><i class="fa fa-circle"></i> Lockscreen</a></li>
                    <li><a href="pages/examples/404.html"><i class="fa fa-circle"></i> 404 Error</a></li>
                    <li><a href="pages/examples/500.html"><i class="fa fa-circle"></i> 500 Error</a></li>
                    <li><a href="pages/examples/blank.html"><i class="fa fa-circle"></i> Blank Page</a></li>
                    <li><a href="pages/examples/pace.html"><i class="fa fa-circle"></i> Pace Page</a></li>
                </ul>
            </li>
        </ul>
        <!-------------------------- Menu 2 -------------------------->
        <ul class="sidebar-menu ocultar" data-widget="tree" id="menuLogistica">
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-share"></i> <span>Multilevel</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle"></i> Level One</a></li>
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-circle"></i> Level One
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="#"><i class="fa fa-circle"></i> Level Two</a></li>
                            <li class="treeview">
                                <a href="#">
                                    <i class="fa fa-circle"></i> Level Two
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>
                                <ul class="treeview-menu">
                                    <li><a href="#"><i class="fa fa-circle"></i> Level Three</a></li>
                                    <li><a href="#"><i class="fa fa-circle"></i> Level Three</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#"><i class="fa fa-circle"></i> Level One</a></li>
                </ul>
            </li>
            <li><a href="https://adminlte.io/docs"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->

</aside>