PYS_Web/Areas/Aprobaciones/Controllers/AyudaBusquedaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PYS_SQL;

namespace PYS_Web.Areas.Aprobaciones.Controllers
{
    public class AyudaBusquedaController : Controller
    {
        private SQL_TA_PERF_USUA sql = new SQL_TA_PERF_USUA();
        private SQL_TA_TIPO_DOCU_SIST sql2 = new SQL_TA_TIPO_DOCU_SIST();
        private SQL_TA_TIPO_EVAL sql3 = new SQL_TA_TIPO_EVAL();
        private SQL_TA_CATE_CARG sql4 = new SQL_TA_CATE_CARG();
        private SQL_TA_TIPO_MEDI_COMU sql5 = new SQL_TA_TIPO_MEDI_COMU();

        // GET: AyudaTabla
        public ActionResult Ayuda_Perfil()
        {
            ViewBag.buscar_TA_PERF_USUA = true;
            ViewBag.V_VB_LIST_TA_PERF_USUA = sql.Listado();
            ViewBag.title = "Tabla Perfil";
            return View("Index");
        }
        public ActionResult Ayuda_Documento()
        {
            ViewBag.buscar_TA_TIPO_DOCU_SIST = true;
            ViewBag.V_VB_LIST_TA_TIPO_DOCU_SIST = sql2.Listado(1);
            ViewBag.title = "Tabla Documentos";
            return View("Index");
        }
        public ActionResult Ayuda_Evaluacion()
        {
            ViewBag.buscar_TA_TIPO_EVAL = true;
            ViewBag.V_VB_LIST_TA_TIPO_EVAL = sql3.Listado();
            ViewBag.title = "Tabla Tipo Evaluación";
            return View("Index");
        }
        public ActionResult Ayuda_Cargo()
        {
            ViewBag.buscar_TA_CATE_CARG = true;
            ViewBag.V_VB_LIST_TA_CATE_CARG = sql4.Listado(1);
            ViewBag.title = "Tabla Categoría Cargo";
            return View("Index");
        }
        public ActionResult Ayuda_Tipo_Medio()
        {
            ViewBag.buscar_TA_TIPO_MEDI_COMU = true;
            ViewBag.V_VB_LIST_TA_TIPO_MEDI_COMU = sql5.Listado();
            ViewBag.title = "Tabla Tipo Medio Comunicación";
            return View("Index");
        }
    }
}

PYS_Web/Areas/RR_HH/Controllers/EvaluacionDesempeñoController.cs
using PYS_Entidad;
using PYS_SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;


namespace PYS_Web.Areas.RR_HH.Controllers
{
    public class EvaluacionDesempeñoController : Controller
    {
        private SQL_TA_EVAL_DESE sql = new SQL_TA_EVAL_DESE();
        private SQL_TA_TIPO_EVAL sqlApoyo = new SQL_TA_TIPO_EVAL();
        private SQL_TA_CATE_CARG sqlApoyo_2 = new SQL_TA_CATE_CARG();

        public ActionResult Index()
        {
            ViewBag.List_Evaluación = sql.Listado(1);

            return View();
        }

        public ActionResult NewEvaluacion()
        {
            return View();
        }

        public ActionResult EditEvaluacion(E_TA_EVAL_DESE obj)
        {   obj.FI_COD_EMPR = 1;
            ViewBag.getEvaluacion = sql.Buscar_Por_Codigo(obj.FS_COD_EVAL_DESE, obj.FI_COD_EMPR);
            return View();
        }


        //public ActionResult ReportEvaluacion()
        //{
        //    List<E_TA_EVAL_DESE> list = new List<E_TA_EVAL_DESE>();
        //    list = sql.Reporte();

        //    string ruta_capa_rep = "\\PYP_Reportes";
        //    string rptRuta = Path.GetDirectoryName(Path.GetDirectoryName(Server.MapPath(""))) + ruta_capa_rep;
        //    ReportDocument rd = new ReportDocument();
        //    rd.Load(Path.Combine(rptRuta, "Rpt_Categoria.rpt"));

        //    rd.SetDataSource(list);
        //    Response.Buffer = false;
        //    Response.ClearContent();
        //    Response.ClearHeaders();
        //    Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
        //    stream.Seek(0, SeekOrigin.Begin);
        //    //Response.AddHeader("Content-Disposition", "inline; filename=Authorization.pdf");
        //    return File(stream, "application/pdf", "Reporte_Categoria.pdf");
        //}
        public void SaveEvaluacion(E_TA_EVAL_DESE obj)
        {
            obj.FS_COD_USCR = "shinta";
            obj.FI_COD_EMPR = 1;
            sql.Insertar(obj);
        }

        [HttpPost]
        public JsonResult Guardar(E_TA_EVAL_DESE model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                SaveEvaluacion(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }
        [HttpPost]
        public JsonResult Actualizar(E_TA_EVAL_DESE model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                UpdateEvaluacion(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }

        public void UpdateEvaluacion(E_TA_EVAL_DESE obj)
        {
            obj.FS_COD_USMO = "shinta";
            obj.FI_COD_EMPR = 1;
            sql.Actualizar(obj);
        }
        public void DeleteEvaluacion(E_TA_EVAL_DESE obj)
        {
            obj.FI_COD_EMPR = 1;
            sql.Eliminar(obj);
        }
        // Validación - Verifica si Campo FS_TIP_EVAL existe en DB 
        [HttpPost]
        public JsonResult validaExistenciaTIP_EVAL(E_TA_TIPO_EVAL obj)
        { 
            obj = sqlApoyo.Buscar_Por_Codigo(obj.FS_TIP_EVAL);
            if (obj.FS_TIP_EVAL != "")
            {
                return Json(true);             
            }
            else
                return Json("Código no existe");
        }
        // Validación - Verifica si Campo FS_COD_CCAR existe en DB 
        [HttpPost]
        public JsonResult validaExistenciaCOD_CCAR(E_TA_CATE_CARG obj)
        {
            obj = sqlApoyo_2.Buscar_Por_Codigo(obj.FS_COD_CCAR, 1);
            if (obj.FS_COD_CCAR != "")
            {
                return Json(true);
            }
            else
                return Json("Código no existe");
        }
        // Validación - Verifica si Campo FS_COD_EVAL_DESE existe en DB 
        [HttpPost]
        public JsonResult validaExistenciaCOD_EVAL_DESE(E_TA_EVAL_DESE obj)
        {
            obj = sql.Buscar_Por_Codigo(obj.FS_COD_EVAL_DESE, 1);
            if (obj.FS_COD_EVAL_DESE == "")
            {
                return Json(true);
            }
            else
                return Json("Código ya existe");
        }
    }
   
}

PYS_Web/Areas/RR_HH/Views/EvaluacionDesempeño/EditEvaluacion.cshtml

@using PYS_Entidad;
@{
    E_TA_EVAL_DESE obj = (E_TA_EVAL_DESE)ViewBag.getEvaluacion;
    Layout = null;
}

<script>
    function frm_buscar_COD_CCAR() {
        $.ajax({
            type: "post", url: "@Url.Action("Ayuda_Cargo", "AyudaBusqueda", new { Area = "Aprobaciones" })",
            success: function (res) {
                $("#ViewModal2").html(res);
                $("#btnViewModal2").click();
            },
            error: function (res) {
                alertify.error("<strong>Error de conexión.</strong>");
            }
        });
    };
    function frm_buscar_TIP_EVAL() {
        $.ajax({
            type: "post", url: "@Url.Action("Ayuda_Evaluacion", "AyudaBusqueda", new { Area = "Aprobaciones" })",
            success: function (res) {
                $("#ViewModal2").html(res);
                $("#btnViewModal2").click();
            },
        error: function (res) {
            alertify.error("<strong>Error de conexión.</strong>");
        }
    });
    };
</script>

<form id="Frm_Evaluacion_Desempeño">
    <div class="modal-dialog modal-editar">
        <div class="modal-content">
            <div class="modal-header text-center ">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" id="btnCerrarEvaluacionEdit">&times;</button>
                <h2>Editar registro</h2>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            @Html.Label("Código Evaluación", new { @class = "control-label" })
                            @Html.TextBoxFor(x => @obj.FS_COD_EVAL_DESE, new
                   {
                       @class = "form-control validaCodigo_3",
                       @id = "TXT_FS_COD_EVAL_DESE",
                       @disabled = "disabled"
                   })

                        </div>
                    </div>
                    <div class="col-sm-8">
                        <div class="form-group">
                            @Html.Label("Observación", new { @class = "control-label" })
                            @Html.TextBoxFor(x => @obj.FS_DES_OBSE, new { @class = "form-control", @id = "TXT_FS_DES_OBSE" })
                            @Html.ValidationMessageFor(x => @obj.FS_DES_OBSE, null, new { @class = "label label-alert help-block" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">
                            @Html.Label("Descripción Evaluación", new { @class = "control-label" })
                            @Html.TextBoxFor(x => @obj.FS_DES_EVAL_DESE, new { @class = "form-control", @id = "TXT_FS_DES_EVAL_DESE" })
                            @Html.ValidationMessageFor(x => @obj.FS_DES_EVAL_DESE, null, new { @class = "label label-alert help-block" })

                        </div>
                    </div>
                    <div class="col-sm-12">
                        <!-- Alineación, col-sm-12-->
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.Label("Código Cargo", new { @class = "control-label" })
                                <div class="input-group">
                                    @Html.TextBoxFor(x => @obj.FS_COD_CCAR, new { @class = "form-control search-query validaCodigo_3", @id = "TXT_FS_COD_CCAR" })
                                    <span class="input-group-btn">
                                        <button id="btnBuscarCodCcar" class="btn btn-transparent btn-sm cancel btn-buscar" data-toggle="tooltip"
                                                title="Buscar" type="button" onclick="frm_buscar_COD_CCAR();" disableValidation="true">
                                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                        </button>
                                    </span>
                                </div>
                                @Html.ValidationMessageFor(x => @obj.FS_COD_CCAR, null, new { @class = "label label-alert help-block" })
                            </div>
                        </div>
                        <div class="col-sm-7">
                            <div class="form-group">
                                <label for="TXT_FS_DES_CCAR" style="visibility:hidden" class="control-label">space</label>
                                <input class="form-control" id="TXT_FS_DES_CCAR" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.Label("Tipo Evaluación", new { @class = "control-label" })
                                <div class="input-group">
                                    @Html.TextBoxFor(x => @obj.FS_TIP_EVAL, new { @class = "form-control search-query validaCodigo_4", @id = "TXT_FS_TIP_EVAL" })
                                    <span class="input-group-btn">
                                        <button id="btnBuscarTipEval" class="btn btn-transparent btn-sm btn-buscar cancel"
                                                data-toggle="tooltip" title="Buscar" type="button"
                                                onclick="frm_buscar_TIP_EVAL();" disableValidation="true">
                                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                        </button>
                                    </span>
                                </div>
                                @Html.ValidationMessageFor(x => @obj.FS_TIP_EVAL, null, new { @class = "label label-alert help-block" })
                            </div>
                        </div>
                        <div class="col-sm-7">
                            <div class="form-group">
                                <label for="TXT_FS_DES_TIPO_EVAL" style="visibility:hidden" class="control-label">space</label>
                                <input class="form-control" id="TXT_FS_DES_TIPO_EVAL" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="modal-footer a-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default" id="btnGrabar" onclick="Actualizar('@obj.FS_COD_EVAL_DESE');">
                                    <span class="glyphicon glyphicon-pencil glyphicon-editar"></span>
                                </button>
                                <button type="button" class="btn btn-default" id="btnCancelar" data-dismiss="modal">
                                    <span class="glyphicon glyphicon-remove glyphicon-cancelar"></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="ViewModal2" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <!--- Body del modal de tabla aquí-->
    </div>
    <div class="col-sm-2 a-left no-padd">
        <button data-toggle="modal" data-target="#ViewModal2" id="btnViewModal2" hidden="hidden" type="button">Mostrar</button>
    </div>
</form>
@Scripts.Render("~/bundles/jsValidacion")

<script type="text/javascript">
    select_FS_COD_CCAR();
    select_FS_TIP_EVAL();
    // Imprimir descripción de Código CARGO
    function select_FS_COD_CCAR() {
        $.ajax({
            type: 'GET',
            url: "@Url.Action("Ayuda_Cargo", "AyudaBusqueda", new { Area = "Aprobaciones" })",
            success: function (data) {
                var codCampo = "#TXT_FS_COD_CCAR";
                var desCampo = "#TXT_FS_DES_CCAR";
                var nomForm = "#Frm_Evaluacion_Desempeño";

                var valCampo = $(codCampo).val();
                var busFila = $(data).find('tbody>tr.row-cate-carg:contains("' + valCampo + '")');
                var colCero = $(busFila).children("td:eq(0)");
                var colUno = $(busFila).children("td:eq(1)");          
                if ($.trim($(colUno).html()) == '' || ($.trim($(colCero).html()) != valCampo) || $.trim(valCampo) == '') {
                    $(nomForm).validate().element(codCampo);
                    $(desCampo).val("");
                }
                else {
                    $(desCampo).val(colUno.html());
                }
            },
        error: function (res) {
            alertify.error("<strong>Error de conexión.</strong>");
        }
    });
    return false;
    }
    // Imprimir descripción de Código TIPO EVAL
    function select_FS_TIP_EVAL() {
        $.ajax({
            type: 'GET',
            url: "@Url.Action("Ayuda_Evaluacion", "AyudaBusqueda", new { Area = "Aprobaciones" })",
            success: function (data) {
                var codCampo = "#TXT_FS_TIP_EVAL";
                var desCampo = "#TXT_FS_DES_TIPO_EVAL";
                var nomForm = "#Frm_Evaluacion_Desempeño";

                var valCampo = $(codCampo).val();
                var busFila = $(data).find('tbody>tr.row-tipo-eval:contains("' + valCampo + '")');
                var colCero = $(busFila).children("td:eq(0)");
                var colUno = $(busFila).children("td:eq(1)");               
                if ($.trim($(colUno).html()) == '' || ($.trim($(colCero).html()) != valCampo) || $.trim(valCampo) == '') {
                    $(nomForm).validate().element(codCampo);
                    $(desCampo).val("");
                }
                else {
                    $(desCampo).val(colUno.html());
                }
            },
        error: function (res) {
            alertify.error("<strong>Error de conexión.</strong>");
        }
    });
    return false;
    }

    function Actualizar(varCodEval) {
        var form = $("#Frm_Evaluacion_Desempeño");

        if (form.validate() && form.valid()) {
            var prm = {
                FS_COD_EVAL_DESE: varCodEval,
                FS_DES_EVAL_DESE: $('#TXT_FS_DES_EVAL_DESE').val(),
                FS_DES_OBSE: $('#TXT_FS_DES_OBSE').val(),
                FS_TIP_EVAL: $('#TXT_FS_TIP_EVAL').val(),
                FS_COD_CCAR: $('#TXT_FS_COD_CCAR').val()
            };
            $.ajax({
                type: "post", url: "@Url.Action("Actualizar", "EvaluacionDesempeño")", data: prm,
                success: function (res) {
                    alertify.success("<strong>Actualizado correctamente.</strong>");
                    Cancelar();
                    $("#btnCerrarEvaluacionEdit").click();
                    $(".modal-backdrop").removeClass();
                },
                error: function (res) {
                    alertify.error("<strong>No se puede actualizar .</strong>");
                }
            });
        };
    };
    $('#TXT_FS_COD_CCAR').keydown(function (e) {
        if (e.keyCode == 13) {
            select_FS_COD_CCAR();
        }
    });
    $('#TXT_FS_TIP_EVAL').keydown(function (e) {
        if (e.keyCode == 13) {
            select_FS_TIP_EVAL();
        }
    });

</script>


PYS_Web/Areas/RR_HH/Views/EvaluacionDesempeño/Index.cshtml
@using PYS_Entidad;
@{
    List<E_TA_EVAL_DESE> list = (List<E_TA_EVAL_DESE>)ViewBag.List_Evaluación;
    Layout = null;
}

<script>
    function Nuevo() {
        $.ajax({
            type: "post", url: "@Url.Action("NewEvaluacion", "EvaluacionDesempeño")",
            success: function (res) {
                $("#ViewModal").empty();
                $("#ViewModal").html(res);
                $("#btnViewModal").click();
            },
            error: function (res) {
                alertify.error("<strong>Error de conexión.</strong>");
            }
        });
    };
    function Editar(varCodCate) {
        var prm = {
            FS_COD_EVAL_DESE: varCodCate
        };
        $.ajax({
            type: "post", data: prm, url: "@Url.Action("EditEvaluacion", "EvaluacionDesempeño")",
            success: function (res) {
                $("#ViewModal").empty();
                $("#ViewModal").html(res);
                $("#btnViewModal").click();
            },
            error: function (res) {
                alertify.error("<strong>Error de conexión.</strong>");
            }
        });
    };

    function Eliminar(codigo) {
        alertify.confirm('¿Está seguro de eliminar el registro?', function (e) {
            if (e) {
                var prm = {
                    FS_COD_EVAL_DESE: codigo
                };
                $.ajax({
                    type: "post", url: "@Url.Action("DeleteEvaluacion", "EvaluacionDesempeño")",
                    data: prm,
                    success: function (res) {
                        alertify.success("<strong>Eliminado correctamente.</strong>");
                        $("#btnEvaluacionDesempeño").click();
                        $(".modal-backdrop").removeClass();
                    },
                    error: function (res) {
                        alertify.error("<strong>No se puede eliminar.</strong>");
                    }
                });
            } else {
                return false;
            };
        });
    };

    function Cancelar() {
        $("#btnEvaluacionDesempeño").click();
    };

    function Imprimir() {

    };

</script>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Evaluacion Desempeño</h3>
    </div>
    <div class="panel-body">
        <div class="content-body">
            <div class="row">
                <div class="col-sm-12">
                    <div class="form-group">
                        <div class="table table-responsive">

                            <div class="clearfix form-group btn-yellow pull-left btn-nuevo-group">
                                <div class="btn-group">
                                    <button id="btnNuevo" class="btn btn-default pull-left" onclick="Nuevo();">
                                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nuevo
                                    </button>
                                </div>
                            </div>

                            <table id="tblEvaluacionDesempeño" class="table table-striped table-bordered table-hover table-condensed" cellspacing="0" width="100%">
                                <thead class="bg-primary">
                                    <tr>
                                        <th style="width:8%">Acciones</th>
                                        <th style="width:11%">Código</th>
                                        <th style="width:44%">Descripción</th>
                                        <th style="width:26%">Observación</th>
                                        <th style="width:7.5%">Cód. Tipo Evaluación</th>
                                        <th style="width:7.5%">Cód. Cargo</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        if (list.Count >= 0 && list != null)
                                        {
                                            foreach (E_TA_EVAL_DESE item in list)
                                            {
                                                <tr>
                                                    <td class="controls  text-center text-middle" style="padding:2px !important">
                                                        <span class="control-table">
                                                            <i data-toggle="tooltip" title="" data-original-title="Cancelar" id="btnCancelar" class="glyphicon glyphicon-remove" style="display: none" onclick="Cancelar();" />
                                                        </span>
                                                        <span class="control-table">
                                                            <i data-toggle="tooltip" title="" data-original-title="Editar" id="Idpencil" class="glyphicon glyphicon-pencil btn btn-transparent" style="color:#92c696;  width:40px !important" onclick="Editar('@item.FS_COD_EVAL_DESE');"></i>
                                                        </span>
                                                        <span class="control-table">
                                                            <i data-toggle="tooltip" title="" data-original-title="Eliminar" class="glyphicon glyphicon-floppy-remove btn btn-transparent" style="color:#e5a6a4; width:40px !important" onclick="Eliminar('@item.FS_COD_EVAL_DESE');"></i>
                                                        </span>
                                                    </td>
                                                    <td class="col-cod-eval-dese">@item.FS_COD_EVAL_DESE</td>
                                                    <td style="text-align:left">@item.FS_DES_EVAL_DESE</td>
                                                    <td style="text-align:left">@item.FS_DES_OBSE</td>
                                                    <td style="text-align:left">@item.FS_TIP_EVAL</td>
                                                    <td style="text-align:left">@item.FS_COD_CCAR</td>

                                                </tr>
                                            }
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-lg" id="ViewModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
</div>
<div class="col-sm-2 a-left no-padd">
    <button data-toggle="modal" data-target="#ViewModal" id="btnViewModal" onclick="" hidden="hidden">Mostrar</button>
</div>

<script>
   $("tr th").css("white-space","nowrap")
    $(function () {
        $("tr th").addClass("text-center");
        $('#tblEvaluacionDesempeño').DataTable({
            responsive: true,
            stateSave: true,
            "stateDuration": 25,
            dom: 'lBfrtip',
            buttons: [
                {
                    extend: 'collection',
                    text: 'Exportar',
                    buttons: [
                        'copy',
                        'excel',
                        'csv',
                        'pdf',
                        'print'
                    ]
                }
            ],
            "lengthMenu": [[5, 10, -1], [5, 10, "Todos"]],
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                }
            }
        });
    });
</script>