PYS_Web/Areas/RR_HH/Controllers/TipoMedioComunicacionController.cs
using PYS_Entidad;
using PYS_SQL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using CrystalDecisions.CrystalReports.Engine;

namespace PYS_Web.Areas.RR_HH.Controllers
{
    public class TipoMedioComunicacionController : Controller
    {
        private SQL_TA_TIPO_MEDI_COMU sql = new SQL_TA_TIPO_MEDI_COMU();

        public ActionResult Index()
        {
            ViewBag.List_Tipo_Medio_Comunicacion = sql.Listado();

            return View();
        }

        public ActionResult NewTipoMedioComu()
        {
            return View();
        }

        public ActionResult EditTipoMedioComu(E_TA_TIPO_MEDI_COMU obj)
        {
            ViewBag.getTipoMedioComunicacion = sql.Buscar_Por_Codigo(obj.FS_TIP_MECO);
            return View();
        }


        //public ActionResult ReportPerfil()
        //{
        //    List<E_TA_TIPO_MEDI_COMU> list = new List<E_TA_TIPO_MEDI_COMU>();
        //    list = sql.Reporte();

        //    string ruta_capa_rep = "\\PYP_Reportes";
        //    string rptRuta = Path.GetDirectoryName(Path.GetDirectoryName(Server.MapPath(""))) + ruta_capa_rep;
        //    ReportDocument rd = new ReportDocument();
        //    rd.Load(Path.Combine(rptRuta, "Rpt_Categoria.rpt"));

        //    rd.SetDataSource(list);
        //    Response.Buffer = false;
        //    Response.ClearContent();
        //    Response.ClearHeaders();
        //    Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
        //    stream.Seek(0, SeekOrigin.Begin);
        //    //Response.AddHeader("Content-Disposition", "inline; filename=Authorization.pdf");
        //    return File(stream, "application/pdf", "Reporte_Categoria.pdf");
        //}
        public void SaveTipoMedioComu(E_TA_TIPO_MEDI_COMU obj)
        {
            obj.FS_COD_USCR = "shinta";
            sql.Insertar(obj);
        }

        [HttpPost]
        public JsonResult Guardar(E_TA_TIPO_MEDI_COMU model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                SaveTipoMedioComu(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }


        [HttpPost]
        public JsonResult Actualizar(E_TA_TIPO_MEDI_COMU model)
        {
            var resp = new ResponseModel
            {
                response = true,
                //redirect="Home/Index",
                error = ""
            };

            if (ModelState.IsValid)
            {
                UpdateTipoMedioComu(model);
            }
            else
            {
                resp.response = false;
            }

            return Json(resp);
        }
        public void UpdateTipoMedioComu(E_TA_TIPO_MEDI_COMU obj)
        {
            obj.FS_COD_USMO = "shinta";
            sql.Actualizar(obj);
        }
        public void DeleteTipoMedioComu(E_TA_TIPO_MEDI_COMU obj)
        {
            sql.Eliminar(obj);
        }

        // Validación - Verifica si Campo FS_TIP_MECO existe en DB 
        [HttpPost]
        public JsonResult validaExistenciaTIP_MECO(E_TA_TIPO_MEDI_COMU obj)
        {
            obj = sql.Buscar_Por_Codigo(obj.FS_TIP_MECO);
            if (obj.FS_TIP_MECO == "")
            {
                return Json(true);
            }
            else
                return Json("Código ya existe");
        }
    }
}

PYS_Web/Areas/RR_HH/Views/TipoMedioComunicacion/EditTipoMedioComu.cshtml
@using PYS_Entidad;
@{
    E_TA_TIPO_MEDI_COMU obj = (E_TA_TIPO_MEDI_COMU)ViewBag.getTipoMedioComunicacion;
    Layout = null;
}

<form id="Frm_Tipo_Medio_Comunicacion">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" id="btnCerrarTipoEdit">&times;</button>
                <h2>Editar registro</h2>
            </div>
            <div class="modal-body">
                <div class="row">

                    <div class="col-sm-4">
                        <div class="form-group">
                            @Html.Label("Código")
                            @Html.TextBoxFor(x => @obj.FS_TIP_MECO, new { @class = "form-control validaCodigo_4", @id = "TXT_FS_TIP_MECO", @disabled = "disabled" })
                            @Html.ValidationMessageFor(x => @obj.FS_TIP_MECO, null, new { @class = "label label-alert help-block" })
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">

                            @Html.Label("Descripción")
                            @Html.TextBoxFor(x => @obj.FS_DES_TIPO_MECO, new { @class = "form-control", @id = "TXT_FS_DES_TIPO_MECO" })
                            @Html.ValidationMessageFor(x => @obj.FS_DES_TIPO_MECO, null, new { @class = "label label-alert help-block" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="modal-footer a-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default" id="btnGrabar" onclick="Actualizar('@obj.FS_TIP_MECO');">
                                    <span class="glyphicon glyphicon-pencil glyphicon-editar"></span>
                                </button>
                                <button type="button" class="btn btn-default" id="btnCancelar" data-dismiss="modal">
                                    <span class="glyphicon glyphicon-remove glyphicon-cancelar"></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
    @Scripts.Render("~/bundles/jsValidacion")
    <script>
        function Actualizar(varCodTipoMeco) {
            var form = $("#Frm_Tipo_Medio_Comunicacion");
            if (form.validate() && $(form).valid()) {
                var prm = {
                    FS_TIP_MECO: varCodTipoMeco,
                    FS_DES_TIPO_MECO: $('#TXT_FS_DES_TIPO_MECO').val()
                };
                $.ajax({
                    type: "post", url: "@Url.Action("Actualizar", "TipoMedioComunicacion")", data: prm,
                    success: function (res) {
                        alertify.success("<strong>Actualizado correctamente.</strong>");
                        Cancelar();
                        $("#btnCerrarTipoEdit").click();
                        $(".modal-backdrop").removeClass();
                    },
                    error: function (res) {
                        alertify.error("<strong>No se puede actualizar.</strong>");
                    }
                });
            };
        };
    </script>


PYS_Web/Areas/RR_HH/Views/TipoMedioComunicacion/Index.cshtml
@using PYS_Entidad;
@{
    List<E_TA_TIPO_MEDI_COMU> list = (List<E_TA_TIPO_MEDI_COMU>)ViewBag.List_Tipo_Medio_Comunicacion;
    Layout = null;
}
<!-- Vista Tipo Medio Comunicación -->
<script>
    function Nuevo() {
        $.ajax({
            type: "post", url: "@Url.Action("NewTipoMedioComu", "TipoMedioComunicacion")",
            success: function (res) {
                $("#ViewModal").empty();
                $("#ViewModal").html(res);
                $("#btnViewModal").click();
            },
            error: function (res) {
                alertify.error("<strong>Error de conexión.</strong>");
            }
        });
    };
    function Editar(varCodTipMeco) {
        var prm = {
            FS_TIP_MECO: varCodTipMeco
        };
        $.ajax({
            type: "post", data: prm, url: "@Url.Action("EditTipoMedioComu", "TipoMedioComunicacion")",
            success: function (res) {
                $("#ViewModal").empty();
                $("#ViewModal").html(res);
                $("#btnViewModal").click();
            },
            error: function (res) {
                alertify.error("<strong>Error de conexión.</strong>");
            }
        });
    };
    function Eliminar(tipo) {
        alertify.confirm('¿Está seguro de eliminar el registro?', function (e) {
            if (e) {
                var prm = {
                    FS_TIP_MECO: tipo
                };
                $.ajax({
                    type: "post", url: "@Url.Action("DeleteTipoMedioComu", "TipoMedioComunicacion")",
                    data: prm,
                    success: function (res) {
                        alertify.success("<strong>Eliminado correctamente.</strong>");
                        $("#btnTipoMedioComu").click();
                        $(".modal-backdrop").removeClass();
                    },
                    error: function (res) {
                        alertify.error("<strong>No se puede eliminar.</strong>");
                    }
                });
            } else {
                return false;
            };
        });
    };

    function Cancelar() {
        $("#btnTipoMedioComu").click();
    };

    function Imprimir() {

    };

</script>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Tipo Medio Comunicación</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group">
                    <div class="table table-responsive">

                        <div class="clearfix form-group btn-yellow pull-left btn-nuevo-group">
                            <div class="btn-group">
                                <button id="btnNuevo" class="btn btn-default pull-left" onclick="Nuevo();">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Nuevo
                                </button>
                            </div>
                        </div>

                        <table id="tblTipoMedioComu" class="table table-striped table-bordered table-hover table-condensed" cellspacing="0" width="100%">
                            <thead class="bg-primary">
                                <tr>
                                    <th style="width:5%">Acciones</th>
                                    <th style="width:8%">Código</th>
                                    <th style="width:87%">Descripción</th>

                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    if (list.Count >= 0 && list != null)
                                    {
                                        foreach (E_TA_TIPO_MEDI_COMU item in list)
                                        {
                                            <tr>
                                                <td class="controls text-center text-middle col-acciones">
                                                    <span class="control-table">
                                                        <i data-toggle="tooltip" title="" data-original-title="Cancelar" id="btnCancelar"
                                                           class="glyphicon glyphicon-remove" style="display: none" onclick="Cancelar();" />
                                                    </span>
                                                    <span class="control-table">
                                                        <i data-toggle="tooltip" title="" data-original-title="Editar" id="Idpencil"
                                                           class="glyphicon glyphicon-pencil btn btn-transparent btn-editar" 
                                                           onclick="Editar('@item.FS_TIP_MECO');"></i>
                                                    </span>
                                                    <span class="control-table">
                                                        <i data-toggle="tooltip" title="" data-original-title="Eliminar" 
                                                           class="glyphicon glyphicon-floppy-remove btn btn-transparent btn-eliminar"
                                                            onclick="Eliminar('@item.FS_TIP_MECO');"></i>
                                                    </span>
                                                </td>
                                                <td class="col-tip-meco">@item.FS_TIP_MECO</td>
                                                <td class="text-left">@item.FS_DES_TIPO_MECO</td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-lg" id="ViewModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
</div>
<div class="col-sm-2 a-left no-padd">
    <button data-toggle="modal" data-target="#ViewModal" id="btnViewModal" onclick="" hidden="hidden">Mostrar</button>
</div>

<script>

    $(function () {
   
        $('#tblTipoMedioComu').DataTable({
            responsive: true,
            dom: 'lBfrtip',
            stateSave: true,
            "stateDuration": 25,
            buttons: [
                {
                    extend: 'collection',
                    text: 'Exportar',
                    buttons: [
                        'copy',
                        'excel',
                        'csv',
                        'pdf',
                        'print'
                    ]
                }
            ],
            "lengthMenu": [[5, 10, -1], [5, 10, "Todos"]],
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                }
            }
        });
    });
</script>

PYS_Web/Areas/RR_HH/Views/TipoMedioComunicacion/NewTipoMedioComu.cshtml
@model PYS_Entidad.E_TA_TIPO_MEDI_COMU
@{
    Layout = null;
}

@using (Html.BeginForm("Guardar", "TipoMedioComunicacion", FormMethod.Post, new { id = "Frm_Tipo_Medio_Comu" }))
{
    <div class="modal-dialog" style="border-radius:10px">
        <div class="modal-content">
            <div class="modal-header text-center">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" id="btnCerrarTipo">&times;</button>
                <h3>Nuevo registro</h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">

                            @Html.Label("Código")
                            @Html.TextBoxFor(x => x.FS_TIP_MECO, new { @class = "form-control validaCodigo_4", @id = "TXT_FS_TIP_MECO" })
                            @Html.ValidationMessageFor(x => x.FS_TIP_MECO, null, new { @class = "label label-alert help-block" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group">

                            @Html.Label("Descripción")
                            @Html.TextBoxFor(x => x.FS_DES_TIPO_MECO, new { @class = "form-control", @id = "TXT_FS_DES_TIPO_MECO" })
                            @Html.ValidationMessageFor(x => x.FS_DES_TIPO_MECO, null, new { @class = "label label-alert help-block" })
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="modal-footer a-center">
                            <div class="btn-group">
                                <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-floppy-disk glyphicon-guardar"></span></button>
                                <button type="button" class="btn btn-default" id="btnCancelar" data-dismiss="modal">
                                <span class="glyphicon glyphicon-remove glyphicon-cancelar"></span></button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@Scripts.Render("~/bundles/jsValidacion")
    <script src="~/Scripts/myScripts/validaCampos.js"></script>
    <script>
        // Función - Recibe aviso de existencia de Código en tabla         
        function validar_existencia_FS_TIP_MECO() {
            $.ajax({
                type: 'GET',
                url: "@Url.Action("Index", "TipoMedioComunicacion")",
                success: function (data) {
                    var valCampo = $('#TXT_FS_TIP_MECO').val();
                    // Busca coincidencia
                    var busColumna = $(data).find('#tblTipoMedioComu > tbody > tr > td.col-tip-meco:contains("' + valCampo + '")');
                    if (busColumna.html() == valCampo) {
                        alertify.confirm('Código ya existe en tabla, ¿desea actualizarlo?', function (e) {
                            if (e) {
                                $('#ViewModal').modal('toggle');
                                $('#ViewModal').one('hidden.bs.modal', function (e) {
                                    Editar(valCampo);
                                })
                            }
                            else {
                                return false;
                            }
                        });
                    }                     
                },
            error: function (res) {
                alertify.error("<strong>Error de conexión.</strong>");
            }
        });        
        }

        $(document).ready(function() {
            $('#Frm_Tipo_Medio_Comu').submit(function() {
                var form = $(this);
                validar_existencia_FS_TIP_MECO();
                if (form.validate() && form.valid())
                {
                form.ajaxSubmit({
                    dataType: 'JSON',
                        type: 'POST',
                        url: form.attr('action'),
                        success: function(res) {
                        if (res.response)
                        {
                            alertify.success("<strong>Registrado correctamente.</strong>");
                            Cancelar();
                                $("#btnCerrarTipo").click();
                                $(".modal-backdrop").removeClass();
                        }
                        else
                        {
                            return false;
                        }
                    },
                        error: function(jqXHR, textStatus, errorThrown) {
                        alertify.error("<strong>" + errorThrown + "</strong>");
                    }
                });
            }
            return false;
        });
    });
    </script>

}

